'''
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"

Example 3:
Input: s = "a", t = "aa"
Output: "a"

Example 4:
Input: s = "ae", t = "aea"
Output: "a"
'''

class Solution(object):
    def findTheDifference(self, s, t):
        temp = {}
        count_s = collections.Counter(s)
        for char in t:
            if char not in count_s or count_s[char] == 0:
                return char
            else:
                count_s[char] -= 1
